# Generated by Django 2.1.15 on 2021-06-19 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationCategory',
            fields=[
                ('categoryID', models.TextField(primary_key=True, serialize=False)),
                ('category', models.TextField()),
            ],
            options={
                'db_table': 'tblApplicationCategory',
            },
        ),
        migrations.CreateModel(
            name='ApplicationItem',
            fields=[
                ('itemID', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'tblApplicationItem',
            },
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('OrderID', models.TextField()),
                ('LoginID', models.TextField(primary_key=True, serialize=False, verbose_name='LineID')),
                ('Name', models.TextField(default='', verbose_name='請輸入全名')),
                ('email', models.TextField(blank=True, default='', max_length=50, verbose_name='ex:xxxx@gmail.com')),
                ('phone', models.TextField(default='', max_length=10, verbose_name='ex:0912345678')),
                ('timeStamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'tblCustomer',
            },
        ),
        migrations.AddField(
            model_name='applicationcategory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.ApplicationItem'),
        ),
    ]
