# Generated by Django 3.2.4 on 2021-06-28 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationCategory',
            fields=[
                ('categoryID', models.TextField(primary_key=True, serialize=False)),
                ('category', models.TextField()),
            ],
            options={
                'db_table': 'tblApplicationCategory',
            },
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('LineID', models.CharField(max_length=1024, primary_key=True, serialize=False, verbose_name='LineID')),
                ('name', models.CharField(default='', max_length=1024, verbose_name='請輸入全名')),
                ('email', models.CharField(blank=True, default='', max_length=1024, verbose_name='ex:xxxx@gmail.com')),
                ('phone', models.CharField(default='', max_length=10, verbose_name='ex:0912345678')),
                ('timeStamp', models.TextField()),
            ],
            options={
                'db_table': 'tblCustomer',
            },
        ),
        migrations.CreateModel(
            name='Promissory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'tblPromissory',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('price', models.TextField()),
                ('orderStatus', models.TextField()),
                ('content', models.TextField(default='')),
                ('consumerID', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.consumer')),
            ],
            options={
                'db_table': 'tblOrder',
            },
        ),
        migrations.CreateModel(
            name='ApplicationItem',
            fields=[
                ('itemID', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('content', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.applicationcategory')),
            ],
            options={
                'db_table': 'tblApplicationItem',
            },
        ),
    ]
