# Generated by Django 3.2.4 on 2021-06-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promissory',
            name='id',
        ),
        migrations.AddField(
            model_name='promissory',
            name='address',
            field=models.CharField(default='1', max_length=1024),
        ),
        migrations.AddField(
            model_name='promissory',
            name='date',
            field=models.CharField(default='1', max_length=1024),
        ),
        migrations.AddField(
            model_name='promissory',
            name='nationalID',
            field=models.CharField(default='1', max_length=1024),
        ),
        migrations.AddField(
            model_name='promissory',
            name='orderID',
            field=models.CharField(blank=True, default='', max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='promissory',
            name='price',
            field=models.IntegerField(default='1800'),
        ),
        migrations.AddField(
            model_name='promissory',
            name='promissoryAddress',
            field=models.CharField(default='1', max_length=1024),
        ),
        migrations.AddField(
            model_name='promissory',
            name='promissoryAmount',
            field=models.CharField(default='1', max_length=1024),
        ),
        migrations.AddField(
            model_name='promissory',
            name='promissoryCourt',
            field=models.CharField(default='1', max_length=1024),
        ),
        migrations.AddField(
            model_name='promissory',
            name='promissoryDate',
            field=models.CharField(default='1', max_length=1024),
        ),
        migrations.AddField(
            model_name='promissory',
            name='promissoryLastDate',
            field=models.CharField(default='1', max_length=1024),
        ),
        migrations.AddField(
            model_name='promissory',
            name='promissoryNote',
            field=models.CharField(default='1', max_length=1024),
        ),
        migrations.AddField(
            model_name='promissory',
            name='promissoryNoticeDate',
            field=models.CharField(default='1', max_length=1024),
        ),
    ]
