# Generated by Django 2.1.15 on 2021-06-20 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumer',
            old_name='LoginID',
            new_name='loginID',
        ),
        migrations.RenameField(
            model_name='consumer',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='consumer',
            old_name='OrderID',
            new_name='orderID',
        ),
    ]
