# Generated by Django 3.2.4 on 2021-06-30 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20210629_0100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='consumerID',
            new_name='consumer',
        ),
    ]
