# Generated by Django 3.2.4 on 2021-07-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_rename_consumerid_order_consumer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='timeStamp',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='promissory',
            name='promissoryAddress',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
