# Generated by Django 3.2.4 on 2021-07-10 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_consumer_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='test',
        ),
    ]
